#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    PageUp,
    PageDown,
    RowStart,
    RowEnd,
    EnterEdit,
    EnterCommand,
    LeaveMode,
    DeleteByte,
    Undo(usize),
    EditHex(u8),
    CommandChar(char),
    CommandBackspace,
    CommandSubmit,
    CommandCancel,
    ForceQuit,
}
