#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    PageUp,
    PageDown,
    RowStart,
    RowEnd,
    EnterInsert,
    EnterReplace,
    ToggleVisual,
    EnterCommand,
    LeaveMode,
    DeleteByte,
    SearchNext,
    SearchPrev,
    Undo(usize),
    EditHex(u8),
    EditBackspace,
    CommandChar(char),
    CommandBackspace,
    CommandSubmit,
    CommandCancel,
    ForceQuit,
}
